Update kafka generator to use cookie from mappings
Kozl0ff/grid-dynamics-p2020-bigdata pull request #13
Opened 2020-10-01 18:20 UTC by Dmitriy-Ivanov-04

2020-10-01 18:41 UTC, S4RPYK3IVl5 requested changes

2020-10-01 18:41 UTC, S4RPYK3IVl5 commented on generators/src/main/java/kafka/pageclickgenerator/PageClickGenerator.java
> +        pageClick.setCookie(getRandomCookieFromMappings());
Why you extracted this single line code at the different function?

2020-10-01 18:41 UTC, S4RPYK3IVl5 commented on generators/src/main/java/kafka/pageclickgenerator/PageClickGenerator.java
> +        // Read URls from the file so that we can randomly use them later
Remove all commentaries, code have to be fully understandable by itself

2020-10-01 18:41 UTC, S4RPYK3IVl5 commented on generators/src/main/java/kafka/pageclickgenerator/PageClickGenerator.java
> +        // Read cookies from CookieEmailMappings file
Comment

2020-10-01 18:41 UTC, S4RPYK3IVl5 commented on generators/src/main/java/peoplegenerator/CookieEmailGenerator.java
>       */
Comment

2020-10-01 18:41 UTC, S4RPYK3IVl5 commented on generators/src/main/java/peoplegenerator/CookieEmailGenerator.java
> +                String data = UUID.randomUUID().toString() + "," + emails.get(random.nextInt(emails.size())) + ","
Use StringBuilder here

2020-10-01 18:43 UTC, Levshunovma commented on generators/src/main/java/kafka/pageclickgenerator/Main.java
>              topic = args[1];
Should we add possibility to get cookieEmailMappingsPath from program arguments like we do with bootstrapServer, topic and urlsPath? Or will we use this class only from IDE?
P.S. This comment refers to lines 12-19, but Github doesn't allow me to add so many lines that aren't in commit.

2020-10-02 08:39 UTC, Levshunovma commented on generators/src/main/java/kafka/pageclickgenerator/Main.java
>              topic = args[1];
Slava said that we'll refactor it later

2020-10-02 08:40 UTC, Levshunovma approved these changes
We'll do some minor fixes later

2020-10-02 08:42 UTC, S4RPYK3IVl5 approved these changes

2020-10-02 08:44 UTC, merged